### ISSUE TITLE
List of MQP

### ISSUE THREAD

**Issue by kurt-hectic** [wmo-im/GTStoWIS2#10]
Which MQP should be officially included in WIS 2.0?

**Comment by petersilva** [comment]
A protocol should be added once we have demonstrated interoperabilty using a free implementation, preferably two.
For now, we have Canada and Germany that have demonstrated some degree of interop using AMQP 0.9. (via rabbitmq) It is likely not difficult to get two implementations working together with MQTT.  

However, interop tests cannot yet be completely formlated for repeatability because the topic structure is not yet uniform (still in flux) so need to nail down the topic structure a bit before moving on to other protocols.

The Canadian stack has been re-factored to make it easy to add protocols such as MQTT and AMQP-1.0, but the work to add them is not yet done.

**Comment by josusky** [comment]
MQTT 3.1.1 and 5.0 have been tested quite extensively (at least) among DWD, JMA and IBL.

**Comment by petersilva** [comment]
Germany and IBL did some work with AMQP 1.0 (rabbitmq native protocol is amqp 0.9, but has plugins for mqtt 3.1, and AMQP 1.0) People were using the mosquitto broker for both v3.1 and v5 exchanges.

**Comment by petersilva** [comment]
When in production, I expect topic selection to be used extensively. in our domestic usage, we have hundreds of clients and few of them subscribe to more than a small percentage of the topics on offer.  The richness of topic based selection is important to preserve when changing protocols. The technique used in the wmo-mesh experiment two years ago, used this: https://github.com/MetPX/sarracenia/blob/master/doc/sr_postv3.7.rst#mapping-to-mqtt  to map topics 
from AMQP to MQTT ... replace '/' with '.' as a topic separator, and prefix the MQTT topic tree with the exchange name, so AMQP:
```

exchange: xpublic
topic: v03.post.surface.de.offenbach_met_com_centre.observation.land.de


```
would become MQTT:
```
xpublic/v03/post/de/offenbach_met_com_centre/observation/land/de
```

@antje-s mentioned use of keys... I worry that the ability to select subtopics in a rich way was perhaps lost in these tests with other protocols, but that's just a guess.  I also asked @josusky about the ability to specify multiple bindings in AMQP. I do not recall the answer.  We only spoke briefly in March. In production use, it is not unusual to have a subscriber with a half-dozen different bindings at the same time. If all we are replicating a complete stream, then topic selection is useless bloat (and we should look at Kafka!), but in production use, where use of a multiple small parts of the whole flow is the rule, it is important.  I admit I have not had a chance to use 1.0, so this might be simple terminology problems.

Can one use "keys" in AMQP 1.0 in a similarly flexible way to use of "topics" in AMQP 0.9 ?  Was it possible to use topics to, on the broker side, select multiple reasonable subsets (mechanism similar to hierachical topic selection of MQTT) of the flows when they were transitioned to AMQP 1.0 or MQTT?

**Comment by josusky** [comment]
Just for your information, I came to know about an ICAO document [Publish/Subscribe Push MEP: Implementation Guidance](https://reference.swim.aero/technical-infrastructure/guidance-for-pub-sub-push-implementation.html) that couples AMQP with a HTTP (REST) as an example of "technology agnostic service design". In my opinion, it is a very unfortunate example because it calls for bespoke software, or did I misunderstand it?

**Comment by petersilva** [comment]
great reference.  I agree with the bespoke part, and it is also specifying things redundantly from the underlying  protocol? it is listing things like Qos, subscription-id, queue... all of which are the opposite of "technology agnostic" ... and it seems to be implementing a custom request/reply mechanism where you implement a server that reads the messages to build subscriptions, when the underlying brokers do that without any need for bespoke code. but just a quick glance... I could have misunderstood.

**Comment by petersilva** [comment]
just to point out that as a result of the discussion in #15 it was concluded server-side filtering is a core requirement, and that led top topics being considered a core requirement of MQP's to be accepted.  At this point, topics are not part of AMQP 1.0 which would seem to exclude it from standards compliance at this point.  Upone further investigation, we may explore a way of mapping the topic concept onto AMQP 1.0, or discover "standard" extensions that permit topics and wildcards, but currently there is no standard for such usage.

The aviation prople are not using pub/sub features of MQP at all, they use AMQP 1.0 as a transliteration of GTS, sending all data through the socket the same way GTS messages have worked for the past 50 years.  It is an unfortunate approach which is fundamentally which requires far more code to be written, rather than using built-in functions available in the pub-sub protocols under consideration.

Therefore currently the standards that are known to work are AMQP 0.8/0.9 and MQTT v3.1 and v5.  As far as we can determine, when industry refers to "AMQP" in the overwhelming majority of cases, the software being referenced is rabbitmq. Interoperability among pre 1.0 amqp implementations is non-existent, and the overwhelming majority of AMQP deployments simply use rabbitmq.  It is thus a de-facto standard.

For MQTT, because of scalability issues, MQTT 3.1 is probably a bad choice. MQTT 5 is likely a good choice for the future, but is not requires some validation, as it has not been used, aside from proof of concept testing in GTS oriented deployments.

So as of right now, if someone says we must publish a list, I would put rabbitmq (amqp 0.9) and MQTTv5 on it.

Future directions... maybe AMQP 1.0 in a few years... more likely is mqttws (MQTT over web sockets), which is already available in some brokers, passes messages over web technology, and just needs some testing and validation.  It is expected that protocols in use will evolve over time.  If I were placing a bet on the future, it would be MQTTws.  I am not currently aware of any testing in the committee of MQTTws.  But it provides no more hope of interop with aviation.

**Comment by antje-s** [comment]
A nice summary from my point of view. I agree that currently we can propose MQTTv5.0 and AMQPv0.9 as common language variants between GISCs. Each center can also provide additional messaging protocols especially for their own AoR, e.g. MQTTv3.1.1 or AMQPv1.0 (which needs to be set up for aviation anyway).  It should also be possible to change the messaging protocol bilaterally between GISCs. It must only be ensured that at least one of the two "basic protocols" can be used to set up a connection. 
For MQTTv5.0, mosquitto can currently be used. Unfortunately, the current plugin from rabbitMQ only supports version 3.1 of MQTT.

**Comment by josusky** [comment]
Let me add, as I am a bit involved in the pilot project in DWD with aviation. It is true that they prefer to send data rather than notifications about data but otherwise, it is the usual publish-subscribe scenario that uses topics. Of course, with AMQP 1.0. The broker is RabbitMQ, but it could equally well be Apache Qpid.
I wrote it here several times, but it seems that I have to repeat it once more. AMQP 1.0 can be used (and is in fact already used) for topic-based distribution. Without any custom development.
Extra effort was needed to be able to effectively exchange data instead of notifications, but that is another story.

**Comment by petersilva** [comment]
@josusky ...  exchanging some messages, likely without filtering being applied, or at best only tested with one implementation, is not representative.  @remygiraud's objection to the use of rabbitmq is the lack of standard.  "Brokers" and "topics" are entirely absent from the AMQP 1.0 standard, so there is not even a way to express how routing keys are interpreted, as it is something, by definition, done by a broker. We don't currently know if apache qpid 1.0 will interpret topic headers in the same way the rabbitmq does, or whether microsoft or ibm, or any other broker will interpret topics the same way.  It is outside the standard.  The point of choosing a standard is to assure interoperability.  No behaviour is defined for topic headers and their processing.

**Comment by josusky** [comment]
@petersilva I see a parallel with HTTP. There is nothing in the standard about sessions or transactions, nevertheless, it is happily used for online banking (and many other applications) that relies on both. The other point is that the AMQP 1.0 is already used in this way, thus it looks strange if we (WMO) say that we cannot use it because it lacks features - that ICAO teams are happily using. We have a saying, that in English could be: "Do not attempt to be more catholic than the Pope".
I will survive if we mention AMQP only as "on bilateral agreement" or something like that, but the image of mercifully smiling Pope will stay in my head ;-)

**Comment by petersilva** [comment]
@josusky: ICAO is not using server-side filtering, or more accurately, they are not using protocols to standardize server-side filtering. Rather they are specifying that end points and/or brokers need to implement server-side filtering, and those methods are left undefined. You yourself pointed out (earlier in this thread) where, in their specification, they indicate that bespoke processing is needed.

ICAO picked OSI/X.400.  Do we value free implementations?  There are none of OSI/X.400. Now they have picked AMQP 1.0, for which there is only qpid proton that we have found. In contrast to many, perhaps dozens, for MQTT. AMQP might have made some sense perhaps five to ten years ago. Today MQTT5 is available and a much better choice. If one of the values of the protocols is good availability of free implementations, then AMQP 1.0 is a poor choice. 

In addition to that, MQTT/ws (MQTT over web sockets) is implemented in mosquitto, and so a path to entirely web-based message queueing is on the horizon.  We will certainly need to have stacks support AMQP 1.0 for interop bridges, but something using AMQP 1.0 is bound to be just as vertical as AMHS, and a poor choice if we are trying to make something more open to widespread adoption.

**Comment by petersilva** [comment]
and another thing... AMQP 1.0 was standardized in 2009.  There is no indication that AMQP 1.1 will ever come out.  It is not a vibrant evolving standard, but rather a dead end.  Contrast with MQTT, which had 3.3 standardized by ISO in 2014, and v5 came out in 2017-2019... like HTTP versions that increment from time to time, locking into a standard that doesn't evolve may be great for stability, but it is awful for keeping up with technological evolution, or addressing protocol weaknesses.

**Comment by remygiraud** [comment]
I fully agree with @petersilva comments.
ICAO has a proven history of making the wrong choice in terms of protocols... X400 being the iconic example.
When I talked with Eurocontrol 2 years ago about AMQP 1.0, I asked them why? and if the did testing before?
The answer to the second question was no. And the "why" part was not much illuminating. So, for the poor of us that will have to send data to aviation, AMQP 1.0 is a must. However, for WMO, I can't see a good reason for making the same mistake :)
When 20ish years ago, WMO decided to move to IP (and FTP), we never really envisaged their equivalent is the ISO world. Who even remember they existed...

**Comment by petersilva** [comment]
I think the direction of ET-AT is that they only want MQTT now.   With that as an decision from
the overarching body, the list is done!
