### ISSUE TITLE
symbolic links

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#21]
Another potential case to support rsync case is symbolic links.  In the Canadian stack, we have a property called *link* with the content of the link being the value.  I'm not sure if having an integrity checksum makes any sense here, as the link itself is the entire body of the "file"... so probably the value of the link itself is enough of a checksum?

**Comment by josusky** [comment]
This "rsync" use case is starting to get to my nerves. I can understand that for you it is not a corner case but in the WMO (GTStoWIS2) contexts ... anyway, I do not want to drop the integrity globally just because of symlinks. What about expecting the applications that know what is a "link" (or unlink) to be smart enough to ignore the integrity value so you can put there whatever you want (empty string?). And ensuring that you do not send such notifications to WIS (or be ready to accept the complains).

**Comment by petersilva** [comment]
One way to keep Integrity:

What if we define an integrity *method* called *link*.  where the *value* is the content of the link ?

Another way... In the Canadian stack, we actually still require the integrity, we have a checksum algorithm just for links, where we calculate the checksum of the link value... which seems pointless to me, but at least it has a more constrained size.  This is an addition to the *link* property in the message.

**Comment by petersilva** [comment]
Since implementations are expected to pass through fields they do not understand, this issue is not a blocker, and can just hang around for a while. I will make a tag "discussion" for now... to mean things that are not settled yet.

**Comment by petersilva** [comment]
payload not an tt-protocols concern: https://github.com/wmo-im/wis2-notification-message
