### ISSUE TITLE
Pertinence of Request/Reply function.

### ISSUE THREAD

**Issue by public-tatsuya-noyori** [wmo-im/GTStoWIS2#30]
MQPs do not have a request-reply function to get lost data on client side.

Also, MQPs does not have a history function to check which data was lost on the client side.

In developing countries, the loss of power supply is possible and the ability to get/find lost data is needed.

**Comment by petersilva** [comment]
Request/Reply was intended to permit recovery of transmission failures over obsolete telecommunications systems that did not provide delivery guarantees.  It may be used as a type of backup/recovery, but it is poorly suited to that.

Properly implemented , the MQP method ensures that data is queued for delivery, and only removed from the queue after the client has successfully downloaded it. A client is supposed to download the file and persist it to a database or disk prior to acknowledging it.  For the vast majority of cases, if a power failure occurs, any "lost" messages will not have been acknowledged.  When the node is returned to service, it will download that data again, without the need to explicitly request what it did not receive.

There is a vulerability where data has not be synchronized to disk after it is written.  The number of such messages should be quite small in practice. That risk can be eliminated by use of synchronous write prior to acknowledgements, but that is likely an unreasonable performance choice.

MQP approach also provides an alternate method of recovery. MQP is used to announce files present on an upstream file service, the downstream country always has the ability to browse the tree on the upstream service and download data it has missed in bulk.  This was not possible with traditional GTS, because there was no accessible file server at the upstream node.

Between the above safeguards and capabilities, it does not seem the reproducing request/reply is appropriate.

There are ways to add request/reply function to MQP should it be deemed necesary.  

It can be discussed further.

**Comment by petersilva** [comment]
ET-AT came up with an architectural approach to this. Have to refer to them.
