### ISSUE TITLE
MQP redundancy Osaka vs. Tokyo

### ISSUE THREAD

**Issue by public-tatsuya-noyori** [wmo-im/GTStoWIS2#31]
When the MQPs server and HTTP server are operated redundantly in Tokyo and Osaka, even if the HTTP server in Tokyo stops, the client is still connected to the MQPs in Tokyo, so it does not automatically switch to Osaka.

MQPs requires failure detection in conjunction with HTTP, The operation will be more complex than GTS.

**Comment by petersilva** [comment]
There are many solutions for failure detection.  Here is one:

If Tokyo advertises data served by Tokyo, and Osaka advertises data served by Osaka:

* a client can subscribe to both... This is not failover, client explicitly connects to both Osaka and Tokyo, downloading all messages all the time.  Whenever it receives a message it downloads from the first place it sees the data being advertised from.  It uses a reception cache with the identity checksums to know what data it has downloaded already.
* client receives product announcement from Osaka...  checks Integrity, and discovers that this is new data it has not downloaded.
* Osaka is down, so attempt to download from Osaka fails.   client saves this message to retry later.
* later, client receives announcement from Tokyo, checks integrity, and it discovers that it is new data it has not downloaded.
* client downloads successfully from Tokyo. Now the integrity sum is present in the client cache.
* later client looks again at the old message from Osaka.  It looks in the cache again, and sees that it has been downloaded.  Osaka message can now be discarded.

There is no need for Osaka and Tokyo to communicate status, there is no need for client to know which is up or not.  When one node fails, it simply receives all data from the remaining node.

**Comment by etoyoda** [comment]
Sorry for jumping into discussion of a group for which I am not a member.

I know almost nothing about already-made agreements for this MQP work, but I'm keen on automation of the operation.
Existing message switching systems (MSS's) of GTS have to be monitored by human operator; s/he closes/opens many circuits when there is a trouble, mostly due to lower layers e.g. TCP connectivity or server hardware.
That style of system is no longer sustainable at least for Japan; this is the decided strategy.
And I believe WMO has agreed to build WIS 2.0 to solve issues of GTS to be more sustainable infrastructure.

Right now all observation data is sent to Tokyo MSS, then it sends the data to Osaka and GTS centers.
When Tokyo is down, Osaka takes over the role.
This style of work _was_ necessary for push protocol, and now deemed to be unacceptable.
Some of you noticed Tokyo MSS went down on 26 January 2021.
Above operation was triggered of course, but that was a total mess.
Tokyo and Osaka MSS's have hundreds of circuits each, and it took hours for Osaka to take over
due to misconfigurations and misunderstanding in a first-time-in-decade event.
http://www.jma.go.jp/jma/press/2102/05b/20210126_shougai3.html
(Re misconfiguration, I'd save time to just refer to speech "Push is dead" by Mr Matteo Dellaqua in CBS held in Asuncion 2021.)

"Push and take-over" is obsolete. We must re-design new style of work.

Again, push is dead.  GTS is something we must overcome.  I'm afraid I don't know the details, but I hope and wish your work achieve this.

**Comment by petersilva** [comment]
Wow. Thank you for the information @etoyoda. I thought @public-tatsuya-noyori was postulating a hypothetical example for planning purposes, and had not understood the nature of the failure in Tokyo. I'm sorry to hear of this hardship. Yes, certainly the idea here is that it is pub/sub.  Ideally both Osaka and Tokyo can subscribe to eachothers' as well as other countries' WIS announcements and collectively obtain data from international sources. Clients should be connected to both centres and download data from whichever centre produces data first.  When one centre goes down, the only effect on downstream would be that the client might notice all of their data is coming from only one centre.

With the current Canadian stack (Sarracenia v2) we don't quite achieve that, as to do the redundancy one must have a local broker on the client, which some consider too complex a requirement, but that's just a weakness of one implementation. We have used this scheme since around 2017 for redundancy in RADAR data acquisition among seven storm prediction centres in Canada, with Edmonton and Montreal as national RADAR data acquisition hubs. Each of the seven offices has their own broker, is transferring messages from both hubs to the local broker. The local broker has a process that weeds out duplicates. Subscribers in each storm prediction centre connect to their local broker.  It has worked as expected during one or two failures in Montreal.  the behaviour during the failures is not well documented... because no-one noticed anything was wrong... they noticed all the other datasets that didn't have the redundancy that RADAR had at that time... and we worked on those... So we have some implicit evidence that the scheme worked fine.

The scheme that uses a local broker is also sensible for our storm prediction centres because we have many clients at the one site.  Having a local broker means there is only a single subscription back to the national hub, with the dozens of local subscribers using the local one. This is similar to how web-accellerators or web-caches work.  Naturally, one could also achieve redundancy at a single site by having two local brokers similarly sharing the load from both national hubs, but we haven't felt that to be necessary.

The next iteration (v3) of the Canadian stack will be fully async and the scheme above should work without any client-side broker, which is better for cases where you truly have only a single subscriber at a site. If you want something that can be implemented Today... I could share some configuration information, perhaps consultations about how to configure the current Sarracenia stack for such a setup. It would require each client to run a broker though. I don't know what sort of IT setup a client has, in this context... a broker is a small piece of software that can be set up in a few minutes, but it is analogous to a small web server at each client site,. The clients would transfer the messages from Osaka and Tokyo to this local broker, and the local downloader would subscribe to this local broker.  If that is too complicated, v3 should be ready in a few months and will remove the need for a client-side local broker.  Or folks could write their own fully async implementation.

The idea above is one way of achieving this sort of redundancy.  One could also have more nodes in the cloud, and get additional redundancy by having, say... five nodes instead of just two Tokyo, Osaka, cloud1, 2, 3... and they would normally share the load, but in the case of the loss of one node, the others would just serve more clients. There are many different possible methods of provisioning such a service, it would depend on local considerations.

**Comment by petersilva** [comment]
the methods of supporting redundancy are based on the message payload and being able to de-duplicate messages from different sources such that redudant subscriptions do not cause problems.
This is simple to do, given the correct notification format.   ET-AT has taken over responsibility for the notification format.
