### ISSUE TITLE
should we drop hours from the topic tree.

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#5]
The original tables provide names for file with different forecast hours.  Transliterating them, one can add a topic per time span in the future.  but it seems like a very unusual case where someone would be interested in the 96 hours forecast, but not the 90 hour one.  it would make sense to remove
interpretation of that table so that products referring to all forecast hours appear under the same topic (ending up as multiple files in a directory.)

**Comment by antje-s** [comment]
in my opinion the prediction hours can be omitted from the topic structure

**Comment by petersilva** [comment]
branch issue005 established with TableC4 lookups overridden by "" (stripping prediction hours from topic tree.)
People can try it out.

**Comment by petersilva** [comment]
also, activated on hpfx.collab.science.gc.ca ... if people want to see what it is like.

**Comment by josusky** [comment]
I do not have any strong feeling neither pro nor contra hours in the topic. But perhaps we are mixing two different concepts here. The topic is related to the notification publishing. The actual notification (message) contains "relPath" element that assigns the data to a leaf in a hierarchy (that we are trying to define in this project). The topic and "relPath" are not necessary the same.
@petersilva Havent we had this discussion already?

**Comment by petersilva** [comment]
My ttables are gone, issue005 tables are gone, overwritten by @antje-s 's version.  So no longer sure where this is.

@josusky  please look at GTStoWIS2/TableC4.json. Also C5 Taken from the WMO tables there are AA's that corespond to each hour of forecast, differentiating it from the analysis and such.  The proposal is to ignore those tables,
in building the topic tree, since anyone interested is likely to be interested in all hours, not just a particular one.

**Comment by josusky** [comment]
@petersilva there are actually two different times. The observed data have usually just one relevant time associated with them (time of observation). While forecasts have two. Initial time of the forecast model run, typically 00:00 UTC, 06:00UTC, etc. and 
the time for which the forecast is made, this is usually expressed as an offset from the initial time.
The Table C4 and C5 in the Manual On GTS refer to this offset.
Now it is relatively rare (but not unseen) to use the model initial time for selection (some models that have slightly more parameters in 00:00 and 12:00 run than in 06:00 and 18:00).
On the other hand it is quite common to pick from the model only certain forecast hours. E.g. model produces forecast for +1 hour, +2, ... +144, ... and the volume is huge so some people take only first 24 hours, or only multiples of 3, or more complex selections like "first 12 hours, then every 3 hours until 72h, then every 6 hours etc".
I think that for models it might be better to offer a (WCS) service that allows all kinds of selection (time and location) and send only notification that the service has new model output available (instead of sending notification for each new GRIB field). But that is for another discussion - services vs data (files).
To conclude, if we want to include also forecast into the hierarchy, we might need two time values. Otherwise we might be fine with none.

**Comment by petersilva** [comment]
@josusky yes, the MQP topics are very coarse, and should be intended for bulkish transfer. Since topics cannot really do  fine-grained selection properly, it is likely better left to OGC/WMS/WCS protocols, that can slice and dice much more finely. Leaving it out of the topic tree does not make selection impossible, it just makes it something that happens on the client side, which is more expensive, but still doable.   

If we put two, the origin date will be different every day... it does not make sense to me, so I lean towards none.

**Comment by petersilva** [comment]
OK made a new upstream issue0005 branch.  People can look it over if they like.  it will merge if no-one objects... eight months so far, no objections... it looks safe to do so.

**Comment by petersilva** [comment]
blessed in meeting.
