### ISSUE TITLE
optimize topic tree no14: national data

### ISSUE THREAD

**Issue by antje-s** [wmo-im/GTStoWIS2#61]
current topic subtree (T1="V"):
national

proposal:
DELETE subtree "national"

**Comment by petersilva** [comment]
I think it would be better to keep a national/ as a reserved place for data for which international topics have not yet been agreed.  I think it could be a useful tag.  otherwise for such data, you would just have to notice that it does not match any known categories, and you have the ambiguity:  error or innovation?

We would want to refine that, naturally.

**Comment by antje-s** [comment]
national was kept
