### ISSUE TITLE
retPath override baseURL also? (W2AT)

### ISSUE THREAD

**Issue by petersilva** [wmo-im/GTStoWIS2#72]
Raoult Beaudoin comment in ET-W2AT.   Able to supply complete URL?
Currrently the retPath is still considered to be relative to the BaseURL in the message.  Raoult was asking if we could supply a complete URL there.  I don't have an opinion at the moment... He mentioned for hydrological case, they might specify a different servers for WAF vs. web services, and so the baseUrl for WAF would be different than needed for web service.  otoh he also mentioned the possibilty of proxies and such to hide the difference... not clear if it is necessary or not.

**Comment by petersilva** [comment]
relevant to #34 also...

**Comment by josusky** [comment]
The reason why we split the URL to the "baseURL" and "relPath" was to be able to re-base the message, i.e. when the data is replicated to a different node, the node can republish the message by changing only the baseURL. But that is the case of a simple mesh (data-pump) file distribution style. I do not think that the re-basing will be used in the case of data from large centres like ECMWF. In such a case the "relPath" serves as a product identifier and "baseURL" + "retPath" defines the service end-point.
The rule is that if "retPath" is not empty the "relPath" is **not** used to construct a URL, it is _only_ an identifier. In other words, you do not need to override the "baseURL", because the notification logically contains just **one URL** and one product identifier. But in simple cases, to shorten the message/notification, we reuse (abuse) the identifier ("relPath") to construct the URL.

**Comment by petersilva** [comment]
yup. That was my initial thinking as well, but it's better to hear it from someone else.

**Comment by petersilva** [comment]
further discussion here: https://github.com/wmo-im/wis2-notification-message
